name: Bump version and release

on:
  workflow_dispatch:
    inputs:
      strategy:
        type: choice
        description: The version bump strategy to use
        required: true
        options:
          - patch
          - minor
          - major

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¨ Checkout development
        uses: actions/checkout@v3
        with:
          ref: development
          fetch-depth: 0

      - name: â¬ Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: â• Bump package.json version
        id: bump
        run: |
          NEW_VERSION=$(yarn version ${{ github.event.inputs.strategy }} | grep -oP "(?<=Bumped to )\d+\.\d+\.\d+")
          git config --local user.name "Github Actions"
          git config --local user.email "actions@github.com"
          git commit -am "Bump to v$NEW_VERSION"
          echo "VERSION=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: ğŸ“¤ğŸ·ï¸ Merge into main and tag
        run: |
          git checkout main
          git merge development
          git tag v${{ steps.bump.outputs.VERSION }}
          HUSKY=0 git push --all --tags
